name: Zig build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2
        with:
          version: 0.14.0
      - run: zig build menu
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: sc64menu
          path: zig-out/bin/sc64menu.n64
